name: 21f3002378@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "17 2 * * *"  # Runs every day at 02:30 UTC

  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update File - hello 
        run: |
          echo "hello" 
          
