name: 21f3002378@ds.study.iitm.ac.in

on:
  schedule:
    - cron: "17 2 * * *"  # Runs every day at 02:30 UTC

  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Git with email 21f3002378@ds.study.iitm.ac.in 
        run: |
          echo "hello" 
          git config --global user.name "github-actions"
          git config --global user.email "21f3002378@ds.study.iitm.ac.in"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git


      - name: Make a change to ensure commit
        run: echo "Update: $(date)" >> log.txt  # Appends timestamp every run

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Automated daily commit"
          git pull --rebase
          git push origin main
          
